{% set version = "2.5.4a" %}
{% set md5 = "0e6dfc5bb7b80924e9f20c653199890e" %}

package:
  name: gnuwin-flex
  version: {{ version }} 

build:
  number: 1

source:
  fn : flex-{{ version }}-1-bin.zip
  url: https://downloads.sourceforge.net/project/gnuwin32/flex/{{ version }}-1/flex-{{ version }}-1-bin.zip
  md5: {{ md5 }}

about:
  home: http://gnuwin32.sourceforge.net/packages/flex.htm
  license: GPLv3
