{% set version = "2.20" %}
{% set sha256 = "453ac9129f5d91ca0cc1819e19fbfbbad4d1d431d69d76b103dc7b77017ff540" %}
{% set tag = "2.20-beta" %}

package:
  name: coda
  version: {{ version }} 

source:
  fn : coda-{{ version }}.tar.gz
  url: https://github.com/stcorp/coda/releases/download/{{ tag }}/coda-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - cmake
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - bison  # [not win]
    - flex  # [not win]
    - m2-bison  # [win]
    - m2-flex  # [win]
    - python
    - numpy
    - zlib
    - hdf4
    - hdf5
    - jpeg

  run:
    - python
    - numpy
    - zlib
    - hdf4
    - hdf5
    - jpeg

about:
  home: https://github.com/stcorp/coda
  license: BSD
  license_file: COPYING

