{% set version = "2.19" %}
{% set sha256 = "82b6bda18bb649946a7c7b1ec7b0302e6ae5315d512ae043b0faf998c91222c9" %}

package:
  name: coda
  version: {{ version }} 

source:
  fn: 3ca3c8baea18150fc7d8b8e3c7936d95d92a6fb7.zip
  url: https://github.com/stcorp/coda/archive/3ca3c8baea18150fc7d8b8e3c7936d95d92a6fb7.zip
#  fn : coda-{{ version }}.tar.gz
#  url: https://github.com/stcorp/coda/releases/download/{{ version }}/coda-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - cmake
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - bison  # [not win]
    - flex  # [not win]
    - m2-bison  # [win]
    - m2-flex  # [win]
    - python
    - numpy
    - zlib
    - hdf4
    - hdf5
    - jpeg

  run:
    - python
    - numpy
    - zlib
    - hdf4
    - hdf5
    - jpeg

about:
  home: https://github.com/stcorp/coda
  license: BSD
  license_file: COPYING

