{% set version = "2.18.1" %}
{% set sha256 = "1e648121f4498098ec06049cf4ca02e8b286370010a245cf676c9036ba282310" %}

package:
  name: coda
  version: {{ version }} 

source:
  fn : coda-{{ version }}.tar.gz
  url: https://github.com/stcorp/coda/releases/download/{{ version }}/coda-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  features:
    - vc9  # [win and py27]

requirements:
  build:
    - python
    - setuptools
    - bison  # [not win]
    - flex  # [not win]
    - m2-bison  # [win]
    - m2-flex  # [win]
    - automake  # [not win]
    - autoconf  # [not win]
    - libtool  # [not win]
    - cmake  # [win]
    - numpy
    - hdf4
    - hdf5

  run:
    - python
    - numpy
    - hdf4
    - hdf5

about:
  home: https://github.com/stcorp/coda
  license: BSD
  license_file: COPYING

