{% set version = "2.20" %}
{% set sha256 = "6561b4a14dcc0a9e7947a0bdbafff2606e1b0df0acba2b4410ecfb671e6ba1ec" %}
{% set tag = version %}

package:
  name: coda
  version: {{ version }} 

source:
  fn : coda-{{ version }}.tar.gz
  url: https://github.com/stcorp/coda/releases/download/{{ tag }}/coda-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - cmake
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - bison  # [not win]
    - flex  # [not win]
    - m2-bison  # [win]
    - m2-flex  # [win]
    - python
    - numpy
    - zlib
    - hdf4
    - hdf5
    - jpeg

  run:
    - python
    - numpy
    - zlib
    - hdf4
    - hdf5
    - jpeg

about:
  home: https://github.com/stcorp/coda
  license: BSD
  license_file: COPYING

