{% set version = "0.4" %}
{% set sha256 = "ad7b0c034b9d51bb5d9cdaa0b00f3ae0055b764d6983937027202a48248fa37c" %}

package:
  name: harp
  version: {{ version }} 

source:
  fn : harp-{{ version }}.tar.gz
  url: https://github.com/stcorp/harp/releases/download/{{ version }}/harp-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - python
    - setuptools
    - flex
    - automake
    - autoconf
    - libtool
    - zlib
    - zip
    - hdf4
    - hdf5
    - numpy
    - zip
    - cffi
    - coda

  run:
    - python
    - coda
    - hdf4
    - hdf5
    - numpy
    - cffi

about:
  home: https://github.com/stcorp/harp
  license: GNU GENERAL PUBLIC LICENSE Version 2, June 1991
  license_family: GPL
  license_file: COPYING

