{% set version = "1.4" %}
{% set sha256 = "88f4977c86b31878c7f55518e7c1cde617f70f4460029c872e01b29573350bc0" %}

package:
  name: harp
  version: {{ version }} 

source:
  path: harp-{{ version }}
#  fn : harp-{{ version }}.tar.gz
#  url: https://github.com/stcorp/harp/releases/download/{{ version }}/harp-{{ version }}.tar.gz
#  sha256: {{ sha256 }}

requirements:
  build:
    - cmake
    - bison  # [not win]
    - flex  # [not win]
    - m2-bison  # [win]
    - m2-flex  # [win]
    - coda
    - python
    - numpy
    - cffi
    - zlib
    - hdf4
    - hdf5
    - jpeg

  run:
    - coda
    - python
    - numpy
    - cffi
    - zlib
    - hdf4
    - hdf5
    - jpeg

about:
  home: https://github.com/stcorp/harp
  license: BSD
  license_file: COPYING

