{% set version = "2.7" %}
{% set md5 = "1c097334c32f7b977093f38b105e7580" %}

package:
  name: gnuwin-regex
  version: {{ version }}

source:
  fn : regex-{{ version }}.zip
  url: https://downloads.sourceforge.net/project/gnuwin32/regex/{{ version }}/regex-{{ version }}-bin.zip
  md5: {{ md5 }}

about:
  home: http://gnuwin32.sourceforge.net/packages/regex.htm
  license: GPLv3

