{% set version = "0.14.4" %}
{% set md5 = "8ba5be33e4208bf9584b176ec606bb06" %}

package:
  name: gnuwin-libintl
  version: {{ version }} 

source:
  fn : libintl-{{ version }}-bin.zip
  url: https://downloads.sourceforge.net/project/gnuwin32/libintl/{{ version }}/libintl-{{ version }}-bin.zip
  md5: {{ md5 }}

about:
  home: http://gnuwin32.sourceforge.net/packages/libintl.htm
  license: GPLv3

